[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.27"
optimizer = true
optimizer_runs = 200

viaIR = true
evm_version = "paris"

ffi = true

remappings = [
    "solady/=lib/solady/src/",
    "@sp1-contracts/=lib/sp1-contracts/contracts/src/",
    "risc0/=lib/risc0-ethereum/contracts/src/",

    # RiscZero
    "openzeppelin/=lib/risc0-ethereum/lib/openzeppelin-contracts/",
]

fs_permissions = [
    { access = "read", path = "test/fixtures"},
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options